<?php
require_once "includes/db.php";
require_once "includes/auth.php";
require_login();
require_role("Admin", "Pharmacist", "Employee");

$page_title = "Invoices";

$rows = $conn->query(
    "SELECT i.*, u.name AS generated_by_name
     FROM invoices i
     LEFT JOIN users u ON i.generated_by = u.user_id
     ORDER BY i.invoice_date DESC, i.invoice_id DESC"
)->fetch_all(MYSQLI_ASSOC);

require_once "includes/header.php";
?>

<input type="text" class="search-box" data-table="data-table" placeholder="Search invoices...">
<table id="data-table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Customer</th>
            <th>Total</th>
            <th>Discount</th>
            <th>Payment</th>
            <th>Generated by</th>
            <th>Date</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($rows as $row) { ?>
        <tr>
            <td><?php echo (int) $row["invoice_id"]; ?></td>
            <td><?php echo h($row["customer_name"]); ?></td>
            <td><?php echo number_format((float) $row["total_amount"], 2); ?></td>
            <td><?php echo number_format((float) $row["discount_applied"], 2); ?></td>
            <td><?php echo h($row["payment_method"]); ?></td>
            <td><?php echo h($row["generated_by_name"] ?? ""); ?></td>
            <td><?php echo h($row["invoice_date"]); ?></td>
            <td><a class="view" href="invoice_print.php?id=<?php echo (int) $row["invoice_id"]; ?>">Print</a></td>
        </tr>
        <?php } ?>
    </tbody>
</table>

<?php require_once "includes/footer.php"; ?>
