import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { api } from '../api/client';
import Modal from '../components/Modal';
import { money } from '../components/Badges';
import FilterToolbar, { FilterSelect } from '../components/FilterToolbar';
import { matchSearch } from '../utils/tableFilter';

const PAYMENT_METHODS = ['Cash', 'Card', 'bKash'];

export default function Invoices() {
  const [rows, setRows] = useState([]);
  const [error, setError] = useState('');
  const [selected, setSelected] = useState(null);
  const [params] = useSearchParams();
  const [search, setSearch] = useState('');
  const [filterPayment, setFilterPayment] = useState('');

  const filteredRows = useMemo(
    () =>
      rows.filter((r) => {
        if (filterPayment && r.payment_method !== filterPayment) return false;
        return matchSearch(r, search, [
          'invoice_id',
          'customer_name',
          'payment_method',
          'generated_by_name',
          'invoice_date',
        ]);
      }),
    [rows, search, filterPayment],
  );

  async function load() {
    try {
      const res = await api('/invoices');
      setRows(res.data);
      setError('');
      const highlight = params.get('highlight');
      if (highlight) {
        const found = res.data.find((r) => String(r.invoice_id) === String(highlight));
        if (found) setSelected(found);
      }
    } catch (err) {
      setError(err.message);
    }
  }

  useEffect(() => {
    load();
  }, []);

  function printInvoice() {
    window.print();
  }

  return (
    <>
      <div className="topbar">
        <h1>Invoices</h1>
      </div>
      {error && <p className="error-text">{error}</p>}
      <FilterToolbar
        search={search}
        onSearchChange={setSearch}
        searchPlaceholder="Search by customer, ID, date, generated by..."
      >
        <FilterSelect
          value={filterPayment}
          onChange={setFilterPayment}
          allLabel="All Payment Methods"
          options={PAYMENT_METHODS.map((p) => ({ value: p, label: p }))}
        />
      </FilterToolbar>
      {rows.length === 0 ? (
        <div className="empty-state">No invoices yet</div>
      ) : filteredRows.length === 0 ? (
        <div className="empty-state">No invoices match your search or filters</div>
      ) : (
        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Customer</th>
              <th>Total</th>
              <th>Discount</th>
              <th>Payment</th>
              <th>Generated By</th>
              <th>Date</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {filteredRows.map((r) => (
              <tr key={r.invoice_id}>
                <td>{r.invoice_id}</td>
                <td>{r.customer_name}</td>
                <td>{money(r.total_amount)}</td>
                <td>{money(r.discount_applied)}</td>
                <td>{r.payment_method}</td>
                <td>{r.generated_by_name || '-'}</td>
                <td>{r.invoice_date}</td>
                <td>
                  <button type="button" className="view" onClick={() => setSelected(r)}>
                    View / Print
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}

      {selected && (
        <Modal title={`Invoice #${selected.invoice_id}`} onClose={() => setSelected(null)} wide>
          <div id="invoice-print">
            <p>
              <strong>Khan Pharmacy</strong>
            </p>
            <p>Customer: {selected.customer_name}</p>
            <p>Date: {selected.invoice_date}</p>
            <p>Payment: {selected.payment_method}</p>
            <table style={{ marginTop: 12 }}>
              <thead>
                <tr>
                  <th>Medicine</th>
                  <th>Qty</th>
                  <th>Price</th>
                  <th>Line</th>
                </tr>
              </thead>
              <tbody>
                {(selected.medicine_details || []).map((d, i) => (
                  <tr key={i}>
                    <td>{d.name}</td>
                    <td>{d.qty}</td>
                    <td>{money(d.price)}</td>
                    <td>{money(d.price * d.qty)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            <p style={{ marginTop: 12 }}>Discount: {money(selected.discount_applied)}</p>
            <p>
              <strong>Total: {money(selected.total_amount)}</strong>
            </p>
            <p>Generated by: {selected.generated_by_name || '-'}</p>
          </div>
          <div className="form-actions no-print">
            <button type="button" className="cancel-btn" onClick={() => setSelected(null)}>
              Close
            </button>
            <button type="button" className="save-btn" onClick={printInvoice}>
              Print
            </button>
          </div>
        </Modal>
      )}
    </>
  );
}
